language: python

python:
  - "3.4"

env: 
  - DJANGO_VERSION=1.11.3

install: 
  - pip install -r requirements/dev.txt
  - pip install coverage

script: 
  - coverage run manage.py test

after-success:
  - coverage report